version: '2'
services:
    cache:
        image: redis
    
    pydbg:
        build: .
        links:
            - cache
        volumes:
            # This is for production (the level db directory, config dependant)
            - /Users/furione/git/py-google-safelist/save:/tmp/py-project/save
        ports:
            - "5000:5000"